-- Add new columns for expanded generation options
ALTER TABLE creations ADD COLUMN IF NOT EXISTS height INTEGER;
ALTER TABLE creations ADD COLUMN IF NOT EXISTS body_type VARCHAR(50);
ALTER TABLE creations ADD COLUMN IF NOT EXISTS style VARCHAR(50);
ALTER TABLE creations ADD COLUMN IF NOT EXISTS colors VARCHAR(255);

-- Add user profile columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS face_shape VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS personal_color VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS height INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(10) DEFAULT 'female';
ALTER TABLE users ADD COLUMN IF NOT EXISTS body_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_images TEXT[];